[versions]
junit = "4.13.1"
retrofit = "2.10.0"
hilt= "2.53.1"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
retrofit = { group = "com.squareup", name = "retrofit2", version.ref = "retrofit" }
hilt = { group = "com.google.dagger.hilt.android", name = "com.google.dagger.hilt.android.gradle.plugin", version.ref = "retrofit" }
