name: Test Android Dependency Updates

on: [workflow_dispatch]

jobs:
  check-dependencies:
    runs-on: ubuntu-latest
    steps:
    - name: Checking Android Dependencies
      uses: JuriKiin/android-dependency-updates@2024.1.9